#!/usr/bin/python
#encoding: UTF-8
#author: str2num

import sys
import os

sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/libbuildmake/")
from entry import main

if __name__ == '__main__':
    main()


